### ISSUE TITLE
Cards disappear

### ISSUE THREAD

**Issue by cv21** [virtual-dev/cardboard#1]
When I open new tab, cards "Quick Settings" and "Recent Downloads" just disappear.
After that sometimes it show again.

**Comment by virtual-dev** [comment]
The [bug in action](http://gyazo.com/544375a5cf49c6f48f2ce7dee80261f6)

**Comment by dotlouis** [comment]
![cards-disappear](https://cloud.githubusercontent.com/assets/1891109/6020831/c5197294-abb0-11e4-834b-56fe0d7d6dcb.gif)

**Comment by dotlouis** [comment]
Yes I'm aware of this issue, thanks for reporting it.
However as I am rewriting the entire extension code I won't be fixing this issue until the v2.0 drops.
v2.0 uses an entire different grid system to display cards that does not cause this flickering.
You can preview it on the branch [material](https://github.com/virtual-dev/cardboard/tree/material)
So it will be resolved then. I hope to be quick as possible to bring the new version on the store.

**Comment by dotlouis** [comment]
I keep this issue open until the new version is merged with master
