### ISSUE TITLE
Recently closed tabs/windows on sync devices

### ISSUE THREAD

**Issue by dotlouis** [virtual-dev/cardboard#28]
https://developer.chrome.com/extensions/sessions

**Comment by virtual-dev** [comment]
Closed by d20178847f4849b9f0a3a98dfc3ce99b4886e4c5

**Comment by virtual-dev** [comment]
Closes d20178847f4849b9f0a3a98dfc3ce99b4886e4c5

**Comment by dotlouis** [comment]
Closed by d20178847f4849b9f0a3a98dfc3ce99b4886e4c5

**Comment by dotlouis** [comment]
Closes on merge
